const birdsList = [
    { id: 1, name: 'Black footed Albatross' },
    { id: 2, name: 'Laysan Albatross' },
    { id: 3, name: 'Sooty Albatross' },
    { id: 4, name: 'Groove billed Ani' },
    { id: 5, name: 'Crested Auklet' },
    { id: 6, name: 'Least Auklet' },
    { id: 7, name: 'Parakeet Auklet' },
    { id: 8, name: 'Rhinoceros Auklet' },
    { id: 9, name: 'Brewer Blackbird' },
    { id: 10, name: 'Red winged Blackbird' },
    { id: 11, name: 'Rusty Blackbird' },
    { id: 12, name: 'Yellow headed Blackbird' },
    { id: 13, name: 'Bobolink' },
    { id: 14, name: 'Indigo Bunting' },
    { id: 15, name: 'Lazuli Bunting' },
    { id: 16, name: 'Painted Bunting' },
    { id: 17, name: 'Cardinal' },
    { id: 18, name: 'Spotted Catbird' },
    { id: 19, name: 'Gray Catbird' },
    { id: 20, name: 'Yellow breasted Chat' },
    { id: 21, name: 'Eastern Towhee' },
    { id: 22, name: 'Chuck will Widow' },
    { id: 23, name: 'Brandt Cormorant' },
    { id: 24, name: 'Red faced Cormorant' },
    { id: 25, name: 'Pelagic Cormorant' },
    { id: 26, name: 'Bronzed Cowbird' },
    { id: 27, name: 'Shiny Cowbird' },
    { id: 28, name: 'Brown Creeper' },
    { id: 29, name: 'American Crow' },
    { id: 30, name: 'Fish Crow' },
    { id: 31, name: 'Black billed Cuckoo' },
    { id: 32, name: 'Mangrove Cuckoo' },
    { id: 33, name: 'Yellow billed Cuckoo' },
    { id: 34, name: 'Gray crowned Rosy Finch' },
    { id: 35, name: 'Purple Finch' },
    { id: 36, name: 'Northern Flicker' },
    { id: 37, name: 'Acadian Flycatcher' },
    { id: 38, name: 'Great Crested Flycatcher' },
    { id: 39, name: 'Least Flycatcher' },
    { id: 40, name: 'Olive sided Flycatcher' },
    { id: 41, name: 'Scissor tailed Flycatcher' },
    { id: 42, name: 'Vermilion Flycatcher' },
    { id: 43, name: 'Yellow bellied Flycatcher' },
    { id: 44, name: 'Frigatebird' },
    { id: 45, name: 'Northern Fulmar' },
    { id: 46, name: 'Gadwall' },
    { id: 47, name: 'American Goldfinch' },
    { id: 48, name: 'European Goldfinch' },
    { id: 49, name: 'Boat tailed Grackle' },
    { id: 50, name: 'Eared Grebe' },
    { id: 51, name: 'Horned Grebe' },
    { id: 52, name: 'Pied billed Grebe' },
    { id: 53, name: 'Western Grebe' },
    { id: 54, name: 'Blue Grosbeak' },
    { id: 55, name: 'Evening Grosbeak' },
    { id: 56, name: 'Pine Grosbeak' },
    { id: 57, name: 'Rose breasted Grosbeak' },
    { id: 58, name: 'Pigeon Guillemot' },
    { id: 59, name: 'California Gull' },
    { id: 60, name: 'Glaucous winged Gull' },
    { id: 61, name: 'Heermann Gull' },
    { id: 62, name: 'Herring Gull' },
    { id: 63, name: 'Ivory Gull' },
    { id: 64, name: 'Ring billed Gull' },
    { id: 65, name: 'Slaty backed Gull' },
    { id: 66, name: 'Western Gull' },
    { id: 67, name: 'Anna Hummingbird' },
    { id: 68, name: 'Ruby throated Hummingbird' },
    { id: 69, name: 'Rufous Hummingbird' },
    { id: 70, name: 'Green Violetear' },
    { id: 71, name: 'Long tailed Jaeger' },
    { id: 72, name: 'Pomarine Jaeger' },
    { id: 73, name: 'Blue Jay' },
    { id: 74, name: 'Florida Jay' },
    { id: 75, name: 'Green Jay' },
    { id: 76, name: 'Dark eyed Junco' },
    { id: 77, name: 'Tropical Kingbird' },
    { id: 78, name: 'Gray Kingbird' },
    { id: 79, name: 'Belted Kingfisher' },
    { id: 80, name: 'Green Kingfisher' },
    { id: 81, name: 'Pied Kingfisher' },
    { id: 82, name: 'Ringed Kingfisher' },
    { id: 83, name: 'White breasted Kingfisher' },
    { id: 84, name: 'Red legged Kittiwake' },
    { id: 85, name: 'Horned Lark' },
    { id: 86, name: 'Pacific Loon' },
    { id: 87, name: 'Mallard' },
    { id: 88, name: 'Western Meadowlark' },
    { id: 89, name: 'Hooded Merganser' },
    { id: 90, name: 'Red breasted Merganser' },
    { id: 91, name: 'Mockingbird' },
    { id: 92, name: 'Nighthawk' },
    { id: 93, name: 'Clark Nutcracker' },
    { id: 94, name: 'White breasted Nuthatch' },
    { id: 95, name: 'Baltimore Oriole' },
    { id: 96, name: 'Hooded Oriole' },
    { id: 97, name: 'Orchard Oriole' },
    { id: 98, name: 'Scott Oriole' },
    { id: 99, name: 'Ovenbird' },
    { id: 100, name: 'Brown Pelican' },
    { id: 101, name: 'White Pelican' },
    { id: 102, name: 'Western Wood Pewee' },
    { id: 103, name: 'Sayornis' },
    { id: 104, name: 'American Pipit' },
    { id: 105, name: 'Whip poor Will' },
    { id: 106, name: 'Horned Puffin' },
    { id: 107, name: 'Common Raven' },
    { id: 108, name: 'White necked Raven' },
    { id: 109, name: 'American Redstart' },
    { id: 110, name: 'Geococcyx' },
    { id: 111, name: 'Loggerhead Shrike' },
    { id: 112, name: 'Great Grey Shrike' },
    { id: 113, name: 'Baird Sparrow' },
    { id: 114, name: 'Black throated Sparrow' },
    { id: 115, name: 'Brewer Sparrow' },
    { id: 116, name: 'Chipping Sparrow' },
    { id: 117, name: 'Clay colored Sparrow' },
    { id: 118, name: 'House Sparrow' },
    { id: 119, name: 'Field Sparrow' },
    { id: 120, name: 'Fox Sparrow' },
    { id: 121, name: 'Grasshopper Sparrow' },
    { id: 122, name: 'Harris Sparrow' },
    { id: 123, name: 'Henslow Sparrow' },
    { id: 124, name: 'Le Conte Sparrow' },
    { id: 125, name: 'Lincoln Sparrow' },
    { id: 126, name: 'Nelson Sharp tailed Sparrow' },
    { id: 127, name: 'Savannah Sparrow' },
    { id: 128, name: 'Seaside Sparrow' },
    { id: 129, name: 'Song Sparrow' },
    { id: 130, name: 'Tree Sparrow' },
    { id: 131, name: 'Vesper Sparrow' },
    { id: 132, name: 'White crowned Sparrow' },
    { id: 133, name: 'White throated Sparrow' },
    { id: 134, name: 'Cape Glossy Starling' },
    { id: 135, name: 'Bank Swallow' },
    { id: 136, name: 'Barn Swallow' },
    { id: 137, name: 'Cliff Swallow' },
    { id: 138, name: 'Tree Swallow' },
    { id: 139, name: 'Scarlet Tanager' },
    { id: 140, name: 'Summer Tanager' },
    { id: 141, name: 'Artic Tern' },
    { id: 142, name: 'Black Tern' },
    { id: 143, name: 'Caspian Tern' },
    { id: 144, name: 'Common Tern' },
    { id: 145, name: 'Elegant Tern' },
    { id: 146, name: 'Forsters Tern' },
    { id: 147, name: 'Least Tern' },
    { id: 148, name: 'Green tailed Towhee' },
    { id: 149, name: 'Brown Thrasher' },
    { id: 150, name: 'Sage Thrasher' },
    { id: 151, name: 'Black capped Vireo' },
    { id: 152, name: 'Blue headed Vireo' },
    { id: 153, name: 'Philadelphia Vireo' },
    { id: 154, name: 'Red eyed Vireo' },
    { id: 155, name: 'Warbling Vireo' },
    { id: 156, name: 'White eyed Vireo' },
    { id: 157, name: 'Yellow throated Vireo' },
    { id: 158, name: 'Bay breasted Warbler' },
    { id: 159, name: 'Black and white Warbler' },
    { id: 160, name: 'Black throated Blue Warbler' },
    { id: 161, name: 'Blue winged Warbler' },
    { id: 162, name: 'Canada Warbler' },
    { id: 163, name: 'Cape May Warbler' },
    { id: 164, name: 'Cerulean Warbler' },
    { id: 165, name: 'Chestnut sided Warbler' },
    { id: 166, name: 'Golden winged Warbler' },
    { id: 167, name: 'Hooded Warbler' },
    { id: 168, name: 'Kentucky Warbler' },
    { id: 169, name: 'Magnolia Warbler' },
    { id: 170, name: 'Mourning Warbler' },
    { id: 171, name: 'Myrtle Warbler' },
    { id: 172, name: 'Nashville Warbler' },
    { id: 173, name: 'Orange crowned Warbler' },
    { id: 174, name: 'Palm Warbler' },
    { id: 175, name: 'Pine Warbler' },
    { id: 176, name: 'Prairie Warbler' },
    { id: 177, name: 'Prothonotary Warbler' },
    { id: 178, name: 'Swainson Warbler' },
    { id: 179, name: 'Tennessee Warbler' },
    { id: 180, name: 'Wilson Warbler' },
    { id: 181, name: 'Worm eating Warbler' },
    { id: 182, name: 'Yellow Warbler' },
    { id: 183, name: 'Northern Waterthrush' },
    { id: 184, name: 'Louisiana Waterthrush' },
    { id: 185, name: 'Bohemian Waxwing' },
    { id: 186, name: 'Cedar Waxwing' },
    { id: 187, name: 'American Three toed Woodpecker' },
    { id: 188, name: 'Pileated Woodpecker' },
    { id: 189, name: 'Red bellied Woodpecker' },
    { id: 190, name: 'Red cockaded Woodpecker' },
    { id: 191, name: 'Red headed Woodpecker' },
    { id: 192, name: 'Downy Woodpecker' },
    { id: 193, name: 'Bewick Wren' },
    { id: 194, name: 'Cactus Wren' },
    { id: 195, name: 'Carolina Wren' },
    { id: 196, name: 'House Wren' },
    { id: 197, name: 'Marsh Wren' },
    { id: 198, name: 'Rock Wren' },
    { id: 199, name: 'Winter Wren' },
    { id: 200, name: 'Common Yellowthroat' },
];

export default birdsList;
